### ISSUE TITLE
Problems installing the software

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#1]
Hello,

I tried installing the software following the exact instructions : 

wget https://github.com/danimaciasperea/Roomberry/archive/V1.1.tar.gz /tmp/
-> results in : 

--2018-08-29 18:12:26--  https://github.com/danimaciasperea/Roomberry/archive/V1.1.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/danimaciasperea/Roomberry/tar.gz/V1.1 [following]
--2018-08-29 18:12:27--  https://codeload.github.com/danimaciasperea/Roomberry/tar.gz/V1.1
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-29 18:12:27 ERROR 404: Not Found.

/tmp/: Scheme missing.

**Comment by danimaciasperea** [comment]
Hi Tony,

You should update the path to the last available release. Right now it would be: 
 `wget https://github.com/danimaciasperea/Roomberry/archive/1.0.0.tar.gz -P /tmp/ `

I forgot to add the -P option to wget. Thanks for noticing.

**Comment by Tokn59** [comment]
Hello,

Thanks !

I reported two more issues in github .. can you please have a look ?

Thanks and kind regards,

Tony
