### ISSUE TITLE
Roomberry installation issue : irobot Library

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#10]
Hello,

when installing the irobot library I get an error : 

wget https://github.com/danimaciasperea/irobot/archive/irobot-1.0.0.tar.gz -P /tmp/irobot/
--2019-01-17 21:29:37--  https://github.com/danimaciasperea/irobot/archive/irobot-1.0.0.tar.gz
Resolving github.com (github.com)... 140.82.118.3, 140.82.118.4
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/danimaciasperea/irobot/tar.gz/irobot-1.0.0 [following]
--2019-01-17 21:29:37--  https://codeload.github.com/danimaciasperea/irobot/tar.gz/irobot-1.0.0
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... **404 Not Found
2019-01-17 21:29:38 ERROR 404: Not Found.**

What is going wrong ? Thank you !

**Comment by danimaciasperea** [comment]
Hi,

To download my fork of the irobot library use this address:
`wget https://github.com/danimaciasperea/irobot/archive/1.0.0.tar.gz -P /tmp/irobot/`

Regards,

Daniel

**Comment by Tokn59** [comment]
Perfect, Thank You !!!
