### ISSUE TITLE
Roomberry installation - Apache

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#12]
I have set up a 2nd PI with Apache2 and OPHP installed and working.

I downloaded the roombery app as follows : 

wget https://github.com/danimaciasperea/Roomberry/archive/1.0.0.tar.gz -P /tmp/
tar -xvf /tmp/1.0.0.tar.gz -C /tmp/ 

Then I copied the contents of /web-app to /var/www/html/

When I enter the URL http://ipoftheapachepi/roomberry.html I get the following screen : 

![roomberry](https://user-images.githubusercontent.com/9215231/51388538-06501a00-1b2a-11e9-85ab-9f27caef4884.JPG)

What's next to do ?

Thanks and kind regards,

Tony

**Comment by danimaciasperea** [comment]
I don't know. What is the error? Where is the Issue?
Please stop opening issues after every step you make in your configuration.
Try to understand how this whole "thing" works and, if after doing it, you find an Issue or an Impediment that stops you from moving further, feel free to open an Issue and I will try to help. But please provide specific information about the problem you find and do not use this as a chat.
In this case, if the Roomberry daemon is not working in the Raspberry Pi W Zero, I don't know what do you expect to see when you open  http://ipoftheapachepi/roomberry.html.
I would suggest you to go back to the instructions and stick to them. Don't pretend to make work the web interface of step 4.2.4 if all the previous steps have not been performed yet (according to another Issue opened #11 you have not still been able to communicate with your Roomba).

**Comment by marcostrullato** [comment]
Hi Daniel, I have the same issue - in the last few days I didn't have time to work on it, I hope this weekend to understand what is going wrong.
@Tokn59 please open the developer mode in the browser, and check in which conditions the wrappers is returning RC=500.

I have noticed it's due to the xmls. 

At the beginning everything works, then probably in the next request, the xmls are not found and are being recreated in the wrong position.

Wired!

Cheers

**Comment by Tokn59** [comment]
I hear you. I will refer from entering issues unless it's a real error. What's the best way for you to ask questions. Current status : 

- Pi Zero fully installed, serial interface tested and working. Need to test via CURL as documented now.
- Pi Web Server : Apache and PHP installed and working. Awaiting final tests on the zero.

So for now, I don't have any questions. I am beginning to understand the architecfture now. Will do further tests next week as I am abroad for now.

Thanks for your support Daniel !
