### ISSUE TITLE
missing multimedia folder

### ISSUE THREAD

**Issue by marcostrullato** [danimaciasperea/Roomberry#13]
Hi Daniel, the script roomberryWrapper.php is not creating the multimedia folder, which is required.
I'm opening this issue just to remember to add the code and open a pull request.

Cheers

**Comment by marcostrullato** [comment]
Hi Daniel,

I've added the fix for the creation of the multimedia folder. 
I coded that after the other pull request, so I'm not 100% sure it's included.
Please let me know otherwise.

Thanks

**Comment by danimaciasperea** [comment]
Hi Marco,

Thanks for your work. I can't find in your commit where have you included this folder creation. However, the default path included in the code (/media) should work by default, considering that it is included in the Raspbian images.

Regards,

Daniel
