### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#2]
in the instructions itb is stated : 

tar -xvf /tmp/1.0.0.tar.gz

**-> this does not place the files in /tmp/Roomberry-1.0.0/roomberry/ BUT in the directory /Roomberry-1.0.0/roomberry/ thus the following lines do not work.**

# Before doing next step, adapt the code to your environment (serial port used, IFTTT Key, etc.)
sudo cp /tmp/Roomberry-1.0.0/roomberry/roomberry.py /usr/local/bin/

**-> Should be sudo cp Roomberry-1.0.0/roomberry/roomberry.py /usr/local/bin/**

and the following line refers to **lib/systemd/system/** where it should read **/lib/systemd/system** ...

sudo cp /tmp/Roomberry-1.0.0/roomberry/roomberry.service lib/systemd/system/

in my humble opinion .. :-)

**Comment by danimaciasperea** [comment]
The directory where the files will be places depends on your current path. Added -C option for clarification. Corrected error in the path to Systemd folder.
