### ISSUE TITLE
System start does not work

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#3]
The instructions say : 

sudo systemctl enable roomberry.service
system roomberry start

2nd command "system roomberry start" results in : 

pi@raspberrypi:~ $ system roomberry start
**bash: system: command not found**

**Comment by Tokn59** [comment]
Shouldn't this be : 

**sudo systemctl start roomberry**

**Comment by danimaciasperea** [comment]
It depends on your user. You are using the default user `pi`. I run and configured the service with `root` user.

**Comment by Tokn59** [comment]
Ok, I was logged in as pi …. Maybe add this to the documentation ?

**Comment by Tokn59** [comment]
TRying this one again ... I am now logged in as root user in Terminal but still get these errors (see screenshot). What am I doing wrong (again) ? Thanks a lot for your support !!!
![system](https://user-images.githubusercontent.com/9215231/51377293-d47b8b00-1b0a-11e9-8411-63a2c66c0266.JPG)

**Comment by danimaciasperea** [comment]
In my guide I used `system`, you are using `systemctl`. The syntax of both command is not the same. To start a service you should do (if running from pi) `sudo systemctl start roomberry` (if you have correctly installed the service first, of course). 

By the way, there is no need to run commands with sudo if logged in as root...

**Comment by Tokn59** [comment]
Correct ! The command was wrong in the documentation where it said "sudo system roomberry start" iso "sudo systemctl start roomberry"

Should have seen this one as well but my PI knowledge is not up to level anymore as I focus more on ESP8266 and Arduino for the moment.

Thanks ! Getting there ! :-)

**Comment by danimaciasperea** [comment]
Well, it should say `service roomberry start.`
Wherever possible I use service and not systemctl.
