### ISSUE TITLE
Start web server

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#4]
Instructions state : 

pi@raspberrypi:~ $ sudo cp -R /tmp/Roomberry-1.0.0/web-app/ /var/www/
cp: cannot stat '/tmp/Roomberry-1.0.0/web-app/': No such file or directory
pi@raspberrypi:~ $ sudo cp -R Roomberry-1.0.0/web-app/ /var/www/

**This should be sudo cp -R Roomberry-1.0.0/web-app/ /var/www/**

Can you please elaborate on the next steps needed to start and reach the webserver ?

THANK YOU !!!

**Comment by danimaciasperea** [comment]
Tony,

You will need a Raspberry Pi (not the Zero) running apache2 with PHP enabled. I think in this [link](https://www.raspberrypi.org/documentation/remote-access/web-server/apache.md) you can find a good guide on how to do this.

Once the server is up and running, place the web-app in the WEB_ROOT path (usually /var/www/). You will probably need to install some additional libraries (php5-curl for instance), but this will depend on what linux distribution you are using. Have a look at the errors logged by apache to find out what libraries you need.

Some further explanations can also be found in my [blog](https://domoticproject.com/roomberry-surveillance-robot-roomba-raspberry-pi-zero-w-camera/).

Thanks!

Dani

**Comment by Tokn59** [comment]
Okay thank you Dani !! Would you mind documenting the apache2 config file for use with Roomberry ?

**Comment by danimaciasperea** [comment]
Tom, the Roomberry does not run Apache. It should be running in another machine.
On the other hand, Apache has not got a single monolithic configuration file, instead it uses several files (and directories). The standard configuration should work just fine if you want to test if your Roomba is working correctly.

**Comment by Tokn59** [comment]
Still trying to run everything on the same device. I installed all the services for IFTTT integration now. No chance this is possible anyway ? Running the APache2 on the Zero as well does not seem to be an issue .. TRied and it works ..

**Comment by danimaciasperea** [comment]
What services for IFTTT integration you mean?
In theory running everything in the same machine will be a mess but possible. There is another person trying it running python in a virtual environment inside the Pi.

**Comment by Tokn59** [comment]
The Web (Curl) stuff ...

I’m installing a 2nd Pi for Apache now ...

Sent from my iPhone

On 18 Jan 2019, at 11:47, Daniel Macías <notifications@github.com<mailto:notifications@github.com>> wrote:


What services for IFTTT integration you mean?
In theory running everything in the same machine will be a mess but possible. There is another person trying it running python in a virtual environment inside the Pi.
