### ISSUE TITLE
xml files

### ISSUE THREAD

**Issue by marcostrullato** [danimaciasperea/Roomberry#5]
Hi Dani, 
For some reason the roomberry.py is creating folders but it's not creating any of the xml files. None of the xml are being created. I'm trying to understand the reason.. do you have any suggestion?

Regards

**Comment by danimaciasperea** [comment]
Hi Marco,

can you check if the user that is running the python program have right to write in the created folders?
Have a look at the log file to find out where the exact problem is.

Regards,

Daniel

**Comment by marcostrullato** [comment]
Hi Daniel,

the permissions were fine. The problem was in the path, in the python api component.
Let me past here my (working) configuration:

PATH_TO_WWW='/home/pi/public_html'
PATH_TO_ROOMBA='/roomba/'
PATH_TO_CAM='/cam/'
PATH_TO_MEDIA='/media/'
PATH_TO_ROOMBA_XML = PATH_TO_ROOMBA + 'roomba.xml'
PATH_TO_CAM_XML = PATH_TO_CAM + 'cam.xml'
PATH_TO_MEDIA_XML = PATH_TO_CAM + 'media.xml'
PATH_TO_SNAP = PATH_TO_CAM + 'snap.jpg'

I still have some issue with the xmls, as initially are being generated where they should be, than the path is changing and they gets generated in PATH_TO_WWW.
Off course once roomberry.py doesn't find anymore the xmls, the scripts stops working properly.

This are the files that gets created:
.
├── [Jan 16 21:12]  cam
│   ├── [Jan 16 21:12]  cam.xml
│   ├── [Jan 16 21:12]  media.xml
│   └── [Jan 16 21:12]  snap.jpg
├── [Jan 16 21:12]  cam.xml
├── [Jan  8 21:19]  css
│   └── [Jan  8 21:19]  custom.css
├── [Jan 16 21:08]  js
│   ├── [Jan  8 21:19]  common.js
│   └── [Jan 16 21:08]  roomberry.js
├── [Jan 16 21:12]  media.xml
├── [Jan 16 21:12]  roomba
│   └── [Jan 16 21:12]  roomba.xml
├── [Jan 16 21:12]  roomba.xml
├── [Jan 14 21:05]  roomberry.html
└── [Jan 14 20:53]  roomberryWrapper.php

and, for example for roomba.xml, these are the timestamp:

stat -c %y ./roomba.xml 
2019-01-16 21:12:23.638163338 +0100
stat -c %y ./roomba/roomba.xml
2019-01-16 21:12:23.598163490 +0100

as you can see the one in the wrong place is more recent.

Tomorrow I'm going to review the code, there must be a bug somewhere.

Cheers

**Comment by danimaciasperea** [comment]
Hi Marco,

Did you introduce the file paths that you want to use in roomberryWrapper.php too? 
Think that this projects has two pieces of software intended to run in two different systems. In your case you are running both of them in the same place. Usually you will have a copy of the file in the Raspberry  Pi and another copy in the Raspberry Pi Zero W.

Regards,

Daniel

**Comment by marcostrullato** [comment]
Hi Daniel, 
now I understand how the code works, I have everything running.
In the last pull request I fixed some issues, so you can close this issues as fixed.

Thanks

**Comment by marcostrullato** [comment]
Ah, I forgot to mention my pull request is fixing also a misbehavior of the tree to navigate the pictures and videos taken.
