### ISSUE TITLE
Roomberry installation issue - Minicom

### ISSUE THREAD

**Issue by Tokn59** [danimaciasperea/Roomberry#9]
Hello Daniel, thanks for sharing this with us ! As I am following your instructions I am encountering some issues. Here's a first one : 

Running on NOOBS 3.0

Instructions say : 

sudo apt-get minicom

This results in an error  : E: invalid operation minicom

Any idea ?

Thanks and kind regards,

Tony

**Comment by danimaciasperea** [comment]
Hi Tokn59. 

I forgot the **install** word.
It should say:
`sudo apt-get install minicom`.

Regards,

Daniel

**Comment by Tokn59** [comment]
Off course, I should have known this. Sorry and thanks for the quick reply Daniel !
